# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-14 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
            options={
                'permissions': (('can_publish', 'can publish artikel'), ('can_edit', 'can edit artikel')),
                'default_permissions': ('add',),
            },
        ),
    ]
