# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='author', max_length=100),
            preserve_default=False,
        ),
    ]
