# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190615_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add',)},
        ),
    ]
