# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-15 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190615_0425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add',), 'permissions': (('can_publish', 'can publish artikel'), ('can_edit', 'can edit artikel'))},
        ),
    ]
