# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jurnal', 'jurnal'), ('Blog', 'blog'), ('Berita', 'berita')], default='Blog', max_length=100),
        ),
    ]
